"""Appendix table for the paper: every quality metric, every direction, every model.

Reads outputs/baseline/<run>.tsv and writes francesco/paper/tables/full_results.tex (a table*, \\input by the paper).
Add a run to RUNS (e.g. the adapter runs for RQ2) and rerun.
Usage: python francesco/analysis/make_full_table.py
"""
import csv
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
BASE = Path("/gpfs/home6/scur0517/outputs/baseline")
OUT = REPO / "francesco/paper/tables/full_results.tex"
RUNS = {"fp16": "ours-beam", "w8": "gptq-w8g128", "w4": "gptq-w4g128", "w3": "gptq-w3g128", "w2": "gptq-w2g128",
        "w3+KD": "gptq-w3g128-as4-kd", "w2+KD": "gptq-w2g128-as4-kd-r64-cont"}
XX_EN = "de-en cs-en is-en zh-en ru-en".split()
EN_XX = "en-de en-cs en-is en-zh en-ru".split()
METRICS = [("bleu", "BLEU", True), ("chrf", "chrF++", True), ("comet-22", "COMET-22", True),
           ("metricx-24", "MetricX-24", False), ("kiwi-22", "CometKiwi-22", True), ("kiwi-xxl", "KIWI-XXL", True),
           ("xcomet-xxl", "XCOMET-XXL", True)]


def load(run):
    out = {}
    for r in csv.DictReader(open(BASE / f"{run}.tsv"), delimiter="\t"):
        if r[run] not in ("", "-"):
            out[(r["pair"], r["metric"])] = float(r[run])
    return out


scores = {name: load(run) for name, run in RUNS.items()}
lab = lambda p: p.replace("-", r"$\rightarrow$")
lines = [r"\begin{table*}[t]", r"\centering", r"\footnotesize", r"\setlength{\tabcolsep}{4.2pt}",
         r"\begin{tabular}{l" + "r" * 5 + "r" + "r" * 5 + "rr}", r"\toprule",
         " & " + " & ".join(map(lab, XX_EN)) + r" & Avg & " + " & ".join(map(lab, EN_XX)) + r" & Avg & All \\"]
for key, name, up in METRICS:
    arrow = r"$\uparrow$" if up else r"$\downarrow$"
    lines += [r"\midrule", rf"\multicolumn{{14}}{{l}}{{\textit{{{name}}} ({arrow})}} \\"]
    fmt = "{:.2f}" if key == "metricx-24" else "{:.1f}"
    for model, s in scores.items():
        a = [s[(p, key)] for p in XX_EN]
        b = [s[(p, key)] for p in EN_XX]
        cells = a + [sum(a) / 5] + b + [sum(b) / 5, sum(a + b) / 10]
        lines.append(model + " & " + " & ".join(fmt.format(v) for v in cells) + r" \\")
lines += [r"\bottomrule", r"\end{tabular}",
          r"\caption{Translation quality of every model in every direction, on WMT'22 (WMT'21 for Icelandic). "
          r"\emph{Avg}: mean over the five directions into or out of English; \emph{All}: mean over all ten. "
          r"XCOMET-XXL, CometKiwi-22 and KIWI-XXL are reference-free; the others use the reference.}",
          r"\label{tab:full}", r"\end{table*}"]
OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text("% Generated by francesco/analysis/make_full_table.py, do not edit by hand.\n" + "\n".join(lines) + "\n")
print(OUT)
